from .error_handler import ErrorHandlerMixin
from .pagination import Page as Page
from .spec import APISpecMixin
from flask.app import Flask
from flask_smorest.blueprint import Blueprint as Blueprint
from typing import Any, Dict, Optional
from webargs.flaskparser import abort as abort

class Api(APISpecMixin, ErrorHandlerMixin):
    spec: Any = ...
    _app: Flask
    def __init__(
        self, app: Optional[Flask] = ..., *, spec_kwargs: Optional[Dict[str, Any]] = ...
    ) -> None: ...
    def init_app(
        self, app: Flask, *, spec_kwargs: Optional[Dict[str, Any]] = ...
    ) -> None: ...
    def register_blueprint(self, blp: Blueprint, **options: Any) -> None: ...
