import marshmallow as ma
from typing import Any, Dict, Tuple

class ErrorSchema(ma.Schema):
    code: Any = ...
    status: Any = ...
    message: Any = ...
    errors: Any = ...

class ErrorHandlerMixin:
    ERROR_SCHEMA: Any = ...
    def handle_http_exception(self, error: Any) -> Tuple[Dict[str, Any], int, Dict]: ...
