from apispec.core import APISpec as APISpec
from flask.wrappers import Response
from typing import Any, Dict, List, Optional, Tuple, Union

def deepupdate(
    original: Dict[str, Any], update: Union[Dict[int, str], Dict[str, Any]]
) -> Union[Dict[int, str], Dict[str, Any]]: ...
def get_appcontext() -> Any: ...
def load_info_from_docstring(
    docstring: Optional[str], *, delimiter: Optional[str] = ...
) -> Dict[str, str]: ...
def unpack_tuple_response(
    rv: Any,
) -> Tuple[Union[Dict, List[int]], Union[None, int, str], Optional[Dict[str, str]]]: ...
def set_status_and_headers_in_response(
    response: Response, status: Union[None, int, str], headers: Optional[Dict[str, str]]
) -> None: ...
def prepare_response(
    response: Dict[str, Any], spec: APISpec, default_response_content_type: str
) -> None: ...
