engines:
    bandit:
        enabled: true
        checks:
            assert_used:
                enabled: false
    duplication:
        enabled: true
        config:
            language:
                python:
                    mass_threshold: 65
exclude_patterns:
    - "tasks/app/db.py"
