version: '3.5'

services:  
    db:
        image: ssfdust/psql_jieba_swsc
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-smorest-admin}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-smorest2019}
            POSTGRES_DB: ${POSTGRES_DB:-smorest-production}
            PGDATA: /data/postgres

    redis:
        image: redis:5.0.9-alpine
        command: redis-server --requirepass "smorest2019"

    rabbitmq:
        image: rabbitmq:3.8.3-management-alpine
        expose: 
            - "15672"
        environment:
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
            RABBITMQ_DEFAULT_VHOST: smorest
            VIRTUAL_HOST: rabbitmq.local

    nginx:
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro

    web:
        image: ssfdust/smorest-sfs
        command: sh scripts/initapp.sh
        volumes:
            - .:/Application 
        restart: on-failure
        expose: 
            - "8000"
        depends_on:
            - db
            - rabbitmq
            - redis
        environment:
            - VIRTUAL_HOST=smorest.local
            - WEB_CONCURRENCY=2

    beat:
        image: ssfdust/smorest-sfs
        command: celery beat --app=smorest_sfs.app:celery_app -S redbeat.RedBeatScheduler
        volumes:
            - .:/Application 
        depends_on:
            - web

    celery:
        image: ssfdust/smorest-sfs
        command: celery --app=smorest_sfs.app:celery_app worker -l INFO -E
        volumes:
            - .:/Application 
        depends_on:
            - web

    pgadmin:
        image: dpage/pgadmin4
        expose: 
            - "80"
        environment:
            - VIRTUAL_HOST=pgadmin.local
            - PGADMIN_DEFAULT_EMAIL=admin@mail.com
            - PGADMIN_DEFAULT_PASSWORD=admin
