OPENAPI_VERSION = '3.0.2'
MODULE_BASE_PREFIX = '/api/v1'

SQLALCHEMY_DATABASE_URI = 'postgresql://smorest-admin:smorest2019@localhost:5432/my-smorest-testing'
SQLALCHEMY_TRACK_MODIFICATIONS = false

SECRET_KEY = '6.ix6D={-+]qK;>Hd9xTQ\iU&!`O&W'
JWT_SECRET_KEY = 'UiXC{?%6vBoqz?F#5w$^J{PNQxhLyW'
JWT_BLACKLIST_ENABLED = true
JWT_BLACKLIST_TOKEN_CHECKS = ['access', 'refresh']
JWT_TOKEN_LOCATION = ['headers', 'query_string']
JWT_QUERY_STRING_NAME = 'token'

BABEL_DEFAULT_LOCALE = 'zh_cn'
BABEL_DEFAULT_TIMEZONE = 'Asia/Shanghai'

MAIL_SERVER = 'smtp.exmail.qq.com'
MAIL_PORT = 465
MAIL_USE_SSL = true
MAIL_USERNAME = ''
MAIL_DEFAULT_SENDER = ''
MAIL_PASSWORD = ''

AMQP_URL = "amqp://"

CELERY_RESULT_BACKEND = 'redis://'
CELERY_BROKER_URL = "amqp://"
CELERY_IMPORTS = ["smorest_sfs.tasks"]
CELERY_ACCEPT_CONTENT = ["json"]

PREFERRED_URL_SCHEME = 'http'
